apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: phpfpm
    layer: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpfpm
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
        - name: phpfpm
          image: php:7.4.33-fpm-alpine3.16
          ports:
            - containerPort: 9000
          resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
          volumeMounts:
            - mountPath: /var/www/html/
              name: contents
      volumes:
        - name: contents
          hostPath:
            path: /mnt/lern-k8s-php
            type: Directory
